### ISSUE TITLE
AI Assist Badge

### ISSUE THREAD

**Issue by samyakkkk** [datavorous/comandi#1]
Hi!

You can use this tool that helps users understand your open-source project with an AI agent trained on it. For example, https://app.commanddash.io/agent?github=https://github.com/datavorous/comandi
many projects mention it as a badge in their readme.

<a href="https://app.commanddash.io/agent/github_datavorous_comandi"><img src="https://img.shields.io/badge/AI-Code%20Agent-EB9FDA"></a>

```
<a href="https://app.commanddash.io/agent/github_datavorous_comandi"><img src="https://img.shields.io/badge/AI-Code%20Agent-EB9FDA"></a>
```

**Comment by datavorous** [comment]
Seems good! Would you mind explaining how it might help? 

P.S. - added it in the readme

**Comment by samyakkkk** [comment]
thanks! The agent is indexed on the code + issues and can users understand how to use it and also the code of the repo. Anyone can ask questions like:

"How can I use COMANDI to convert natural language instructions into command-line commands?"
"How does the prompt templates work behind the scenes"
"What are the steps to contribute to the COMANDI project?"

and get custom AI generated answers for the repo :) hope this helps.
