### ISSUE TITLE
Specify line numbers along with filename

### ISSUE THREAD

**Issue by KineticTactic** [datavorous/comandi#2]
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify line numbers so that it can help me analyse only a certain section of code. This would be especially handy for bigger files, which currently errors out as the HTTP request gets too big. 

**Describe the solution you'd like**
Specify line numbers after the filename separated by colon.
```py
understand main.py:25,28
```

**Describe alternatives you've considered**
None

**Additional context**
Maybe in the future we can add a crude parser so that we can specify a function name. But that would have to be language dependent and is probably out of scope for now.

**Comment by datavorous** [comment]
Fixed!
